version: "3"
services:
  
  postgres:
    image: postgres:14
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_DB=petclinic
  
