package ba.sake.sharaf.petclinic.domain.models

import java.time.LocalDate
import io.scalaland.chimney.dsl.*
import ba.sake.sharaf.petclinic.db.models.pet.VisitRow

case class Visit(
    date: LocalDate,
    description: String
):
  def toRow: VisitRow = this
    .into[VisitRow]
    .withFieldConst(_.id, -1) // autogenerated by db
    .withFieldRenamed(_.date, _.visit_date)
    .transform

object Visit:
  def fromRow(row: VisitRow) = row
    .into[Visit]
    .withFieldRenamed(_.visit_date, _.date)
    .transform
