package ba.sake.sharaf.petclinic.web.models

import java.time.LocalDate
import io.scalaland.chimney.dsl.*
import ba.sake.formson.FormDataRW
import ba.sake.validson.Validator
import ba.sake.sharaf.petclinic.common.*
import ba.sake.sharaf.petclinic.domain.models.Pet

// create/edit pet form data
case class UpsertPetForm(
    name: String,
    birthDate: LocalDate,
    petType: PetType
) derives FormDataRW:
  def toNewPet: Pet = this
    .into[Pet]
    .withFieldConst(_.id, -1) // autogenerated by db
    .withFieldConst(_.visits, Seq.empty)
    .transform

object UpsertPetForm:

  val empty = UpsertPetForm("", LocalDate.now(), PetType.bird)

  given Validator[UpsertPetForm] = Validator
    .derived[UpsertPetForm]
    .notBlank(_.name)
    .and(_.birthDate, _.isBefore(LocalDate.now()), "must be in the past")

  def fromPet(p: Pet): UpsertPetForm = p.transformInto[UpsertPetForm]
