package ba.sake.sharaf.petclinic.web.models

import io.scalaland.chimney.dsl.*
import ba.sake.formson.FormDataRW
import ba.sake.validson.Validator
import ba.sake.sharaf.petclinic.domain.models.Owner

case class UpsertOwnerForm(
    firstName: String,
    lastName: String,
    address: String,
    city: String,
    telephone: String
) derives FormDataRW:
  def toNewOwner: Owner = this
    .into[Owner]
    .withFieldConst(_.id, -1) // autogenerated by db
    .withFieldConst(_.pets, Seq.empty)
    .transform

object UpsertOwnerForm:

  val empty = UpsertOwnerForm("", "", "", "", "")

  given Validator[UpsertOwnerForm] = Validator
    .derived[UpsertOwnerForm]
    .and(_.firstName, !_.isBlank(), "must not be blank")
    .and(_.lastName, !_.isBlank(), "must not be blank")
    .and(_.address, !_.isBlank(), "must not be blank")
    .and(_.city, !_.isBlank(), "must not be blank")
    .and(_.telephone, t => t.trim.size == 10 && t.forall(_.isDigit), "must be 10-digit number")

  def fromOwner(o: Owner): UpsertOwnerForm = o.transformInto[UpsertOwnerForm]
